requirements-dev: pin flake8 to < 4
due to incompatible changes in flake8.
This works around errors like

AttributeError: '_io.StringIO' object has no attribute 'buffer'
Signed-off-by: Konrad Weihmann <kweihmann@outlook.com>